# Generated by Django 4.2 on 2024-05-25 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='api_id',
        ),
    ]
