# Generated by Django 4.2 on 2024-05-28 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games_app', '0002_remove_game_api_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['name']},
        ),
    ]
