# Generated by Django 4.2 on 2025-01-23 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games_app', '0008_franchise_alter_game_options_game_serial_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['franchise__name', 'year', 'clear_name']},
        ),
        migrations.RemoveField(
            model_name='game',
            name='serial_number',
        ),
        migrations.AlterField(
            model_name='game',
            name='franchise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='games_app.franchise'),
        ),
    ]
