# Generated by Django 4.2 on 2025-01-23 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games_app', '0010_alter_game_options_game_ordering_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='clear_name',
        ),
    ]
