# Generated by Django 4.2 on 2025-01-23 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games_app', '0011_remove_game_clear_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['ordering_name', 'year', 'name']},
        ),
    ]
