# Generated by Django 4.2 on 2024-05-29 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games_app', '0003_alter_game_options_alter_genre_options'),
        ('players_app', '0002_rename_portfolio_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameCards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_finished', models.BooleanField(default=False)),
                ('hours_played', models.IntegerField(default=0)),
                ('avatar_names', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(default='')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games_app.game')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players_app.profile')),
            ],
            options={
                'unique_together': {('game', 'profile')},
            },
        ),
    ]
