# Generated by Django 4.2 on 2024-05-29 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games_app', '0003_alter_game_options_alter_genre_options'),
        ('players_app', '0003_gamecards'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GameCards',
            new_name='GameCard',
        ),
    ]
