# Generated by Django 4.2 on 2024-05-29 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players_app', '0004_rename_gamecards_gamecard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamecard',
            name='avatar_names',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='gamecard',
            name='hours_played',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamecard',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
