# Generated by Django 4.2 on 2024-06-03 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players_app', '0006_profile_is_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamecard',
            name='hours_played',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
