# Generated by Django 4.2 on 2024-06-05 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games_app', '0004_perspective_game_rating_game_summary_and_more'),
        ('players_app', '0007_alter_gamecard_hours_played'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gamecard',
            unique_together={('profile', 'game')},
        ),
    ]
