# Generated by Django 4.2 on 2024-06-09 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players_app', '0010_rename_review_link_url_gamecard_review_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players_app.profile')),
            ],
        ),
    ]
