# Generated by Django 4.2 on 2024-06-09 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players_app', '0011_playerrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamecard',
            name='notes',
            field=models.TextField(blank=True, max_length=1023, null=True),
        ),
        migrations.AlterField(
            model_name='playerrequest',
            name='text',
            field=models.TextField(max_length=1023),
        ),
    ]
