# Generated by Django 4.2 on 2024-06-21 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players_app', '0012_alter_gamecard_notes_alter_playerrequest_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamecard',
            options={'ordering': ['game__clear_name']},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['user__username']},
        ),
    ]
