# Generated by Django 4.2 on 2024-06-21 12:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players_app', '0013_alter_gamecard_options_alter_profile_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31)),
                ('date', models.DateField(default=datetime.datetime.today)),
                ('description', models.TextField()),
            ],
        ),
    ]
