# Generated by Django 4.2 on 2024-06-21 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players_app', '0014_version'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='version',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='version',
            name='news',
            field=models.TextField(blank=True, null=True),
        ),
    ]
