# Generated by Django 4.2 on 2025-01-23 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players_app', '0015_alter_version_options_version_news'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamecard',
            options={'ordering': ['game__ordering_name']},
        ),
    ]
