# Generated by Django 4.2 on 2025-01-24 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players_app', '0016_alter_gamecard_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamecard',
            options={'ordering': ['game__ordering_name', 'game__year', 'game__name']},
        ),
    ]
